development:
  redis_url: ENV['REDIS_SOCKET_URL'] || 'redis://redis:6379/0'
  access_logs_disabled: false

production:
  redis_url: ENV['REDIS_SOCKET_URL'] || 'redis://redis:6379/3'
  access_logs_disabled: false
