# Make it possible to switch adapters by passing the ACTION_CABLE_ADAPTER env variable.
# For example, you can use it fallback to the standard Action Cable in staging/review
# environments (by setting `ACTION_CABLE_ADAPTER=redis`).
development:
  adapter: redis
  url: <%= ENV['REDIS_SOCKET_URL'] || 'redis://redis:6379/0' %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_SOCKET_URL'] || 'redis://redis:6379/3' %>